import { useEffect, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import PageShell from "../components/PageShell";
import { API_URL } from "../lib/api";

function EditProfile(){
  const token=localStorage.getItem("token");const navigate=useNavigate();const [profile,setProfile]=useState(null);const [error,setError]=useState("");const [saving,setSaving]=useState(false);
  useEffect(()=>{if(!token)return;fetch(`${API_URL}/me`,{headers:{Authorization:`Bearer ${token}`}}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.message);setProfile(data.user);localStorage.setItem("user",JSON.stringify({id:data.user.id,name:data.user.name,email:data.user.email}));}).catch(err=>setError(err.message));},[token]);
  if(!token)return <Navigate to="/login"/>;
  async function submit(e){e.preventDefault();setSaving(true);setError("");try{const response=await fetch(`${API_URL}/me`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({name:profile.name,bio:profile.bio,avatar_url:profile.avatar_url})});const data=await response.json();if(!response.ok)throw new Error(data.message);localStorage.setItem("user",JSON.stringify({id:profile.id,name:profile.name,email:profile.email}));navigate(`/users/${profile.id}`);}catch(err){setError(err.message);}finally{setSaving(false);}}
  return <PageShell><main className="content-shell form-page"><section className="form-intro"><p className="eyebrow">Your identity</p><h1 className="page-title">Your profile.</h1><p className="page-subtitle">Help readers know the person behind the words.</p></section>{!profile?<div className="form-card"><div className="spinner"/>{error||"Loading profile…"}</div>:<form className="form-card" onSubmit={submit}>{error&&<p className="message">{error}</p>}<div className="form-group"><label htmlFor="name">Display name</label><input id="name" value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} minLength="2" maxLength="60" required/></div><div className="form-group"><label htmlFor="bio">Bio</label><textarea id="bio" className="short-textarea" value={profile.bio||""} onChange={e=>setProfile({...profile,bio:e.target.value})} maxLength="280" placeholder="What do you write about?"/><p className="form-hint">{(profile.bio||"").length}/280</p></div><div className="form-group"><label htmlFor="avatar">Avatar image URL</label><input id="avatar" type="url" value={profile.avatar_url||""} onChange={e=>setProfile({...profile,avatar_url:e.target.value})} placeholder="https://example.com/photo.jpg"/></div><div className="form-actions"><button type="button" className="button button-secondary" onClick={()=>navigate(-1)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving?"Saving…":"Save profile"}</button></div></form>}</main></PageShell>;
}
export default EditProfile;
