import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import PageShell from "../components/PageShell";
import { API_URL, formatDate, getExcerpt } from "../lib/api";

function Profile(){
  const {id}=useParams();const token=localStorage.getItem("token");const [data,setData]=useState(null);const [following,setFollowing]=useState(false);const [error,setError]=useState("");
  const storedUser=JSON.parse(localStorage.getItem("user")||"null");const isOwn=String(storedUser?.id)===String(id);
  useEffect(()=>{const controller=new AbortController();async function load(){try{const response=await fetch(`${API_URL}/users/${id}`,{signal:controller.signal});const result=await response.json();if(!response.ok)throw new Error(result.message);setData(result);if(token&&!isOwn){const status=await fetch(`${API_URL}/users/${id}/follow-status`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal});if(status.ok)setFollowing((await status.json()).following);}}catch(err){if(err.name!=="AbortError")setError(err.message);}}load();return()=>controller.abort();},[id,token,isOwn]);
  async function toggleFollow(){if(!token)return;const response=await fetch(`${API_URL}/users/${id}/follow`,{method:following?"DELETE":"POST",headers:{Authorization:`Bearer ${token}`}});if(response.ok){setFollowing(!following);setData((current)=>({...current,user:{...current.user,followers_count:Number(current.user.followers_count)+(following?-1:1)}}));}}
  return <PageShell><main className="content-shell">{error?<div className="state-card"><strong>Profile unavailable</strong>{error}</div>:!data?<div className="state-card"><div className="spinner"/>Loading profile…</div>:<><section className="profile-hero"><div className="profile-avatar">{data.user.avatar_url?<img src={data.user.avatar_url} alt=""/>:data.user.name.charAt(0).toUpperCase()}</div><div className="profile-copy"><p className="eyebrow">Writer profile</p><h1 className="page-title">{data.user.name}</h1><p className="page-subtitle">{data.user.bio||"This writer is still working on their introduction."}</p><div className="profile-stats"><span><strong>{data.user.blogs_count}</strong> stories</span><span><strong>{data.user.followers_count}</strong> followers</span><span><strong>{data.user.following_count}</strong> following</span></div></div><div>{isOwn?<Link className="button button-secondary" to="/profile/edit">Edit profile</Link>:token?<button className={`button ${following?"button-secondary":"button-primary"}`} onClick={toggleFollow}>{following?"Following":"Follow"}</button>:<Link className="button button-primary" to="/login">Sign in to follow</Link>}</div></section><div className="section-heading"><div><h2>Published stories</h2><p>{data.user.name} joined {formatDate(data.user.created_at)}</p></div></div><div className="blog-grid profile-grid">{data.blogs.length?data.blogs.map((blog)=><article className="blog-card" key={blog.id}><div className="card-meta"><time>{formatDate(blog.created_at)}</time></div><h3><Link to={`/blogs/${blog.id}`}>{blog.title}</Link></h3><p>{getExcerpt(blog.content,180)}</p><span className="card-stats">♥ {blog.likes_count} · ◯ {blog.comments_count}</span></article>):<div className="state-card"><strong>No stories yet</strong>Check back later.</div>}</div></>}</main></PageShell>;
}
export default Profile;
